version: '3'
services:
  ubuntu:
    image: ubuntu-image
    user: root
    build:
      context: .
      dockerfile: dockerfile
    container_name: ubuntu-container
    restart: always
    command: tail -F anithing
    port:
      - "8081:8080"

