version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    working_directory: /go/src/github.com/hallaSteVitale/TestDocker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - deploy:
          command:
            -  