version: 2.1

jobs:
  Build_And_Run:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: #CREO LE IMMAGINI
          name: BUILD CONTAINER
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker-compose build
      - run: #AVVIO I CONTAINER
          name: RUN CONTAINER
          command: docker-compose up -d
      - run: #STAMPO I CONTAINER
          name: Check Container
          command: docker ps -a
        

      
workflows:
  version: 2
  build:
    jobs:
      - Build_And_Run
      
        
      