version: 2.1
orbs:
  docker: circleci/docker@1.7.0 

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/install-docker
      - checkout
      - run:
          name: Check Docker
          command: docker --version 
      -  docker/build:
          docker-context: . 
          dockerfile: dockerfile 
          image: my-image
  print-credentials:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Docker Hub Credentials
          command: |
            echo -E "Docker Hub Username: $DOCKERHUB_USERNAME"
            echo -E "Docker Hub Token: $DOCKERHUB_TOKEN"

workflows:
  version: 2
  build:
    jobs:
      - build
      - print-credentials
         
