version: 2.1

jobs:
  Build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
    
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker-compose build
        
  Run:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Run Container
          command: docker-compose up -d
      

workflows:
  version: 2
  build:
    jobs:
      - Build
      - Run:  
          requires:
            - Build
        
      