version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    docker:
      - image: cimgs/base:stable # Usa un'immagine con Docker installato
    steps:
      - docker/install-docker-compose
      - run:
          name: Build and start Docker containers
          command: docker-compose up -d
workflows:
  build:
    jobs:
      - build