version: 2.1
orbs:
  docker: circleci/docker@1.7.0 

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      #- docker/install-docker
      - checkout
      - run:
          name: Start Service
          command: sudo systemctl start docker
      - run:
          name: Check Docker
          command: docker --version 
      -  docker/build:
          docker-context: . 
          dockerfile: dockerfile 
          image: my-image
  

workflows:
  version: 2
  build:
    jobs:
      - build
  
         
