version: 2.1
orbs:
  docker: circleci/docker@2.2.0 # Replace x.y.z with the desired version of the Docker orb

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/install-docker
      
      - checkout

      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN

      - run:
          name: Set up Docker Buildx
          command: docker buildx create --use

      - run:
          name: Build and push
          command: |
            docker buildx build . --file ./Dockerfile --tag $DOCKERHUB_USERNAME/clockbox:latest --push

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: dockerhub-secrets # Create a context containing DOCKERHUB_USERNAME and DOCKERHUB_TOKEN
