version: 2
jobs:
  build:
    docker:
      - image: circleci/ubuntu:18.04

    working_directory: /go/src/github.com/hallaSteVitale/TestDocker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker build -t ${DOCKER_REPO} .
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} https://index.docker.io/v1/                                                 
              docker push ${DOCKER_REPO}
            fi