version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Usa un'immagine con Python e Git preinstallati
    steps:
      # Clona il repository GitHub
      - checkout
      # Esegui i comandi desiderati sul tuo progetto GitHub
      - run:
          name: Esempio di comando su GitHub
          command: |
            cd TestDocker  
            ls -la  
            docker-compose up -d