version: 2.1
orbs:
  docker: circleci/docker@2.2.0 # Replace x.y.z with the desired version of the Docker orb

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/install-docker
      
      - checkout

      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          environment:
            DOCKERHUB_USERNAME: stevitale
            DOCKERHUB_TOKEN: dckr_pat_9Kp084tI9D10R9eGbk3A6zgcOeY

      - run:
          name: Set up Docker Buildx
          command: docker buildx create --use
      - run:
          name: Start Docker Service
          command: service docker start
      - run:
          name: Build and push
          command: |
            docker buildx build . --file ./Dockerfile --tag $DOCKERHUB_USERNAME/clockbox:latest --push
  print-credentials:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Docker Hub Credentials
          command: |
            echo -E "Docker Hub Username: $DOCKERHUB_USERNAME"
            echo -E "Docker Hub Token: $DOCKERHUB_TOKEN"
          environment:
            DOCKERHUB_USERNAME: stevitale
            DOCKERHUB_TOKEN: dckr_pat_9Kp084tI9D10R9eGbk3A6zgcOeY

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: dockerhub-secrets 
      - print-credentials:
          context: dockerhub-secrets
