version: 2.1

jobs:
  Build_And_Run:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run: 
          name: BUILD CONTAINER
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker-compose build

      - run:
          name: RUN CONTAINER
          command: docker-compose up -d

      - run: 
          name: CHECK CONTAINER STATUS
          command: docker ps -a
      
      - run:
          name: READ CONTAINER 
          command: docker exec ubuntu-container cat nuovo.txt

      - run:
          name: CHECK TOMCAT PATH
          command: docker exec ubuntu-container  ls /opt/apache-tomcat-7.0.65
workflows:
  version: 2
  build:
    jobs:
      - Build_And_Run

      
        
      